= Repository Administrator Responsibilities

== Administrator rotation schedule:

Every 2 weeks a different project member assumes the role of repository administrator.
Signing up to be administrator is voluntary.

== Administrator responsibilities:

As the administrator you are in charge of performing the following duties:

=== Being the Point of Contact for general issues related to the Supplementary Style Guide repository

* You are the point of contact in case other contributors experience issues with the repository.
When people reach out to you about an issue, try to fix it if you can.
If you cannot fix the issue, report to it to a member of the initiative who can.

=== Maintaining the Style Guide site on GitHub

* Ensure that the style guide site is available and displayed correctly.
* Create pull requests to update the README.md, GUIDELINES.adoc and the Contribution guide, if necessary.

=== Driving resolution of open issues

* Review issues submitted to the Supplementary Style Guide GitHub repository.
* Ensure that discussion on open issues is moving forward consistently. If the discussion does not progress, notify CCS Style Council members and report any issues that need the attention of your peers at the next meeting.
* Update issue priority labels according to decisions made in meetings.
* Close issues that are resolved.

=== Driving the completion of pull requests

* Ensure that contributors are submitting pull requests on prioritized open issues.
* Also ensure that work on open pull requests is moving forward consistently.
* Ensure that at least 3 members of the CCS Style Council (Link) review and approve every contribution before merging it. You can be one of the 3.
* If a contribution is not reviewed or approved for longer than 1 week, reach out to individual Style Council members and ask them to review and approve the contribution.
* Merge contributions that are approved by 3 or more Style Council members.
