= About this guide

[IMPORTANT]
**This document is a work in progress.**

This guide provides style guidelines and preferred term usage for link:https://www.redhat.com/[Red Hat] product and cross-product solution documentation. It is intended to be used as a supplement to _The IBM Style Guide_, which is the primary source of guidance for Red Hat product documentation.

This guide was created by the Red Hat Customer Content Services team, who is responsible for producing product documentation for Red Hat customers. It may also be used by upstream communities who want to align more closely with the standards used by Red Hat product documentation.

= How to use this guide

When looking for style guidance, reference this guide first, because it overrides certain guidance from _The IBM Style Guide_. If you must deviate from the guidance in either guide, notify the style council by opening an link:https://github.com/redhat-documentation/doc-style/issues[issue]. This way, the deviation can be discussed by the style council and included in this guide.
