
[[technical-examples]]
= Technical examples

[[commands-with-root-privileges]]
== Commands requiring root privileges

Some commands require root privileges to run. Users without root privileges must first do one of the following to run such a command:

* Preface the command with `sudo` to temporarily change their current privileges.
* Run `su -` to switch to the root user account.

Use the following guidelines when you document commands that require root privileges:

* If a command requires a temporary switch to root privileges, use the `sudo` command at the beginning of the sample command syntax rather than the `su -` command.
* If you include a shell prompt in a sample command, always show the correct prompt for a regular user (`$`) or a user with root privileges (`#`).
+
[NOTE]
====
Do not rely solely on a shell prompt in a sample command to indicate the required privilege level to run a command.
If you include a shell prompt to indicate that a user with root privileges must run the command, also include a statement about this requirement in the step text, the introductory text, or the prerequisites.
====
+
* When a sample command includes `sudo`, use the `$` prompt, not `#`, as shown in the following example: 
+
[source,terminal]
----
$ sudo systemctl start firewalld
----
+
* If multiple commands in a procedure require root privileges, add introductory content to tell the user about the requirement. 
The following example shows one way that you could integrate a requirement for root access into the introduction for a procedure:
+
.Example AsciiDoc
----
Some tasks in this procedure require root privileges, which you can get temporarily by prefixing commands with `sudo`.
----

.Additional resources
* link:https://www.redhat.com/sysadmin/difference-between-sudo-su[Exploring the differences between sudo and su commands in Linux]

[[ip-addresses-and-mac-addresses]]
== IP addresses and MAC addresses

Use the IP and MAC address ranges that are reserved for documentation purposes to avoid the likelihood of conflicts and confusion.

[[reserved-ip-addresses]]
=== Reserved IP addresses

Reserved IPv4 addresses for documentation are defined in link:https://www.rfc-editor.org/rfc/rfc5737.html[RFC 5737]:

[cols="1,1,1", options="header"]
|===
|Network
|Subnet mask
|Assignable addresses

|192.0.2.0
|24
|192.0.2.1 - 192.0.2.254

|198.51.100.0
|24
|198.51.100.1 - 198.51.100.254

|203.0.113.0
|24
|203.0.113.1 - 203.0.113.254
|===

Reserved IPv6 addresses for documentation are defined in link:https://www.rfc-editor.org/rfc/rfc3849.html[RFC 3849]:

[cols="1,1,1", options="header"]
|===
|Network
|Prefix
|Assignable addresses

|2001:0DB8::
(long form: 2001:0DB8:0:0:0:0:0:0)
|32
|2001:0db8:0000:0000:0000:0000:0000:0000 - 2001:0db8:ffff:ffff:ffff:ffff:ffff:ffff

|===

See the _IBM Style_ guide for additional guidance on using IP addresses in documentation.

[[reserved-mac-addresses]]
=== Reserved MAC addresses

Reserved MAC addresses for documentation are defined in link:https://www.rfc-editor.org/rfc/rfc7042.html#section-2.1.2[RFC 7042]:

* For unicast: 00:00:5E:00:53:00 - 00:00:5E:00:53:FF
* For multicast: 01:00:5E:90:10:00 - 01:00:5E:90:10:FF

[[long-code-examples]]
== Long code examples

All code blocks (regardless of length) must be necessary, accurate, and helpful. Code blocks must be as copy-and-paste friendly as possible, with the exception of variables and callouts. The length of the block is irrelevant, within reason, if the code block follows these guidelines.

[[code-example-syntax-highlighting]]
== Syntax highlighting

Provide the source language if it is supported by the Red{nbsp}Hat Customer Portal toolchain. Do not use the `bash` source language for terminal commands. It incorrectly interprets the number sign (#) as a comment instead of the prompt for a root command.

.Example AsciiDoc


  [source,yaml]
  ----
  collections:
        - name: amazon.aws
          source: https://galaxy.ansible.com/api/v2/collections
          version: 1.2.1
  ----


// TODO: Add new style entries alphabetically in this file
