[[formatting]]
= Formatting

[[commands-in-code-blocks]]
== Commands in code blocks

Use a single command per code block for each procedure step. This approach helps with readability and makes it possible for the copy button in code blocks to work correctly.

By default, use bold formatting for commands in code blocks to visually distinguish the commands from their lead-in sentences and from the command prompts and example outputs. For consistency, use bold formatting for commands even when no command output is shown in the code block.

[NOTE]
====
To apply formatting in a code block, you must use the `quotes` link:https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/[AsciiDoc substitution].
====

.Example AsciiDoc: A command and its output in a code block

  Verify that the `libvirt` default network is active and configured to start automatically:
  
  [subs="+quotes"]
  ----
  # *virsh net-list --all*
  Name      State    Autostart   Persistent
  --------------------------------------------
  default   active   yes         yes
  ----


This example renders as follows in HTML:

====
Verify that the `libvirt` default network is active and configured to start automatically:

[subs="+quotes"]
----
# *virsh net-list --all*
Name      State    Autostart   Persistent
--------------------------------------------
default   active   yes         yes
----
====

Do not use bold formatting for the output, unless you need to highlight a specific part of it. When you do emphasize a non-command item in a code block, you are not required to bold the command.

For both commands and outputs in code blocks, observe the correct markup for user-replaced values, as described in xref:user-replaced-values[] and xref:user-replaced-values-xml[].

[[date-formats]]
== Date formats

Follow the _IBM Style_ guide advice of _day Month year_ for date formats, for example, 3 October 2019.

When the format _day Month year_ causes a presentation or clarity issue, use _Month day, year_ (for example, October 3, 2019) instead.

[[non-breaking-spaces]]
== Non-breaking spaces

Use a _non-breaking space_ (`+{nbsp}+`) between the words "Red" and "Hat". The non-breaking space prevents an automatic line break from separating the two words onto two lines.
A _non-breaking space_ prevents the company name from splitting across a line break.

.Example AsciiDoc: Non-breaking space
----
Before you begin to customize the installer, download the Red{nbsp}Hat-provided boot images.
----

[product-names-versions-ref]]
== Product names and version references

Whenever you refer to the name of your product in full, or in its abbreviated form, or when you refer to the major and minor version of your product, avoid using hard-coded references and use attributes instead.
Only use hard-coded version references if the version that you are referring to in a particular case never changes.

=== Attribute file

Define attributes for product name and product version and store them in a dedicated attributes file for each set of product documentation.
For examples of where you can store the shared attributes file inside your documentation repository, see the link:https://github.com/redhat-documentation/modular-docs/blob/mod-doc-repo-example/_artifacts/document-attributes.adoc[Example modular documentation repository].
Include the attributes file at the beginning of the `master.adoc` files of all titles in your documentation set:

.Example AsciiDoc: Attribute file included in a master.adoc file
[subs="+quotes"]
----
\include::__<path_to_directory_with_attributes_file>__/attributes.adoc[]
----

=== Minimum required attributes

Define attributes for the following values in each documentation set.
Note that the attribute names used in this section are only meant as examples.
You can use different attribute names:

The name of the product:: Use the product name attribute for all instances of the product name where possible.
Avoid using hard-coded product names.
For example:
+
.Example AsciiDoc: Product name attribute
----
:name-product: Red{nbsp}Hat JBoss Enterprise Application Platform
----

The abbreviated form of the product name:: If it is necessary for your product, you can use an attribute to store a shortened version of the name of your product, for example:
+
.Example AsciiDoc: Abbreviated product name attribute
----
:name-product-abbreviated: JBoss EAP
----

The major and minor version of the product:: Use an attribute for the product version in cases where the product version can change with each release and the content is still correct.
For example:
+
.Example AsciiDoc: Product version attributes
----
:version-product-minor: 1.11
:version-product-patch: 1.11.6
----
+
[NOTE]
====
Do not use the product version attribute if the version should not change.
For example, if a feature was introduced in a certain version, the version should be hard-coded.
====

You might create additional attributes according to what your documentation requires.
For example, you might combine existing product name attributes to create compound names of products or components:

.Example attributes for compound names of product components
----
:name-runtime-spring-boot: Spring Boot
:name-runtime-vertx: Eclipse Vert.x
:name-spring-reactive: {name-runtime-spring-boot} with {name-runtime-vertx} reactive components
----

[[single-step-procedures]]
== Single-step procedures

When a procedure contains only one step, use an unnumbered bullet.

For example:
====
* Install the `dnf-automatic` package.
====

[[titles-and-headings]]
== Titles and headings

Write all titles and headings, including the titles of product documentation guides and Knowledgebase articles, in sentence-style capitalization. Do not use headline-style capitalization.

.Examples
* _Composing a customized RHEL system image_
* _Configuring the node port service range_
* _How to perform an unsupported conversion from a RHEL-derived Linux distribution to RHEL_


[[user-replaced-values]]
== User-replaced values

A _user-replaced value_, also known as a replaceable or variable value, is a value that the user must replace with a value that is relevant for their situation. User-replaced values are often found in places such as code blocks, file paths, and commands.

Use descriptive names for user-replaced values and follow this general format: _<value_name>_.

[NOTE]
====
For XML code blocks, see the guidance on xref:#user-replaced-values-xml[user-replaced values for XML].
====

Ensure that user-replaced values have the following characteristics:

* Surrounded by angle brackets (`< >`)
* Separated by underscores (`_`) for multi-word values
* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme
* Italicized
* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value
* If you want to use a user-replaced value in example output, format the replaceable value with italics and in angle brackets. Alternatively, if you choose to use an example value instead, do not italicize the example value and do not place it in angle brackets.

.Example AsciiDoc: User-replaced value in a paragraph

----
Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.
----

This example renders as follows in HTML:

====
Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.
====

To italicize a user-replaced value in a code block, you must add an attribute to apply text formatting, such as `subs="+quotes"` or `subs="normal"`, to the attribute list of the code block.

.Example AsciiDoc: User-replaced value in a code block

  [subs="+quotes"]
  ----
  $ *oc describe node __<node_name>__*
  ----

This example renders as follows in HTML:

====
[subs="+quotes"]
----
$ *oc describe node __<node_name>__*
----
====

.Example AsciiDoc: User-replaced value in an output example

  [subs="+quotes"]
  ----
  connection.id:              __<profile_name>__
  connection.uuid:            b6cdfa1c-e4ad-46e5-af8b-a75f06b79f76
  connection.type:            802-3-ethernet
  connection.interface-name:  enp7s0
  ----

This example renders as follows in HTML:

====
[subs="+quotes"]
----
connection.id:              __<profile_name>__
connection.uuid:            b6cdfa1c-e4ad-46e5-af8b-a75f06b79f76
connection.type:            802-3-ethernet
connection.interface-name:  enp7s0
----
====

[[user-replaced-values-xml]]
== User-replaced values for XML

Because XML uses angle brackets (`< >`), the xref:#user-replaced-values[default guidance] for user-replaced values does not work well for it. If you are using user-replaced values in an XML code block, use the following format: _${value_name}_.

Ensure that user-replaced values in XML have the following characteristics:

* Surrounded by curly braces and preceded by a dollar sign (`${ }`)
* Separated by underscores (`_`) for multi-word values
* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme
* Italicized
* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value

.Example AsciiDoc: User-replaced value for an XML element

  [source,xml,subs="+quotes"]
  ----
  <ipAddress>__${ip_address}__</ipAddress>
  ----

This example renders as follows in HTML:

====
[source,xml,subs="+quotes"]
----
<ipAddress>__${ip_address}__</ipAddress>
----
====

.Example AsciiDoc: User-replaced value for an XML attribute

  [source,xml,subs="+quotes"]
  ----
  <oauth2-introspection client-id="__${client_id}__"/>
  ----

This example renders as follows in HTML:

====
[source,xml,subs="+quotes"]
----
<oauth2-introspection client-id="__${client_id}__"/>
----
====


// TODO: Add new style entries alphabetically in this file
