[[formatting]]
= Formatting

[[commands-in-code-blocks]]
== Commands in code blocks

Use a single command per code block for each procedure step. Separate a command and its related example output into individual code blocks. This approach helps with readability and makes it possible for the copy button in code blocks to work correctly.

By default, use bold formatting for commands in code blocks to visually distinguish the commands from their lead-in sentences and from the command prompts and example outputs. For consistency, use bold formatting for commands even when no command output is shown in the code block.

[NOTE]
====
To apply formatting in a code block, you must use the `quotes` link:https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/[AsciiDoc substitution].
====

.Example AsciiDoc: A command and its output in separate code blocks

  Verify that the `libvirt` default network is active and configured to start automatically:

  [subs="+quotes"]
  ----
  # *virsh net-list --all*
  ----
 
  [subs="+quotes"]
  ----
  Name      State    Autostart   Persistent
  --------------------------------------------
  default   active   yes         yes
  ----


This example renders as follows in HTML:

====
Verify that the `libvirt` default network is active and configured to start automatically:

[subs="+quotes"]
----
# *virsh net-list --all*
----

[subs="+quotes"]
----
Name      State    Autostart   Persistent
--------------------------------------------
default   active   yes         yes
----
====

For commands and command outputs in code blocks, observe the correct markup for user-replaced values, as described in xref:user-replaced-values[] and xref:user-replaced-values-xml[].

[[explain-commands-variables-in-code-blocks]]
== Explanation of commands and variables used in code blocks

To explain commands, lines of code, or variables (user-replaced values) in a code block, follow the code block with the relevant explanation or description of the elements, using the following guidelines. Do not use callouts.

* Use a simple sentence to explain or describe a single line of command, variable, option, or parameter.
+
.Example AsciiDoc: A simple sentence explaining a single command

[source,terminal]
----
$ hcp create cluster <platform> --help 
----
+
Use the `hcp create cluster` command to create and manage hosted clusters. The supported platforms are `aws`, `agent`, and `kubevirt`.

* Use a bulleted list to describe the structure of a sample YAML file or explain multiple lines of code in a code block.
**  List the explanations in the order in which they appear in the code block.
+
.Example AsciiDoc: A bulleted list explaining the structure of an YAML file

[source,yaml]
----
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
...
  tasks: 
  - name: build-image
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: buildah
      - name: namespace
        value: openshift-pipelines
    workspaces: 
    - name: source 
      workspace: shared-workspace 
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - fetch-repository
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces: 
    - name: source
      workspace: shared-workspace
    runAfter:
      - build-image
...
----
+
** `workspaces` specifies the list of pipeline workspaces shared between the tasks defined in the pipeline. A pipeline can define as many workspaces as required. In this example, only one workspace named `shared-workspace` is declared.
** `tasks` specifies the definition of tasks used in the pipeline. This snippet defines two tasks, `build-image` and `apply-manifests`.
** `tasks.name.workspaces` specifies the list of task workspaces used in the `build-image` and `apply-manifests` tasks. A task definition can include as many workspaces as it requires. However, it is recommended that a task uses at most one writable workspace. In this example, both the tasks share a common task workspace named `source`, which in turn shares the pipeline workspace named `shared-workspace`.

* Use a definition list to explain multiple options, parameters, variables, placeholders, or UI elements.
**  List the parameters/variables in the order in which they appear in the code block.
**  Introduce definition lists with "where:" and begin each variable description with "Specifies".
+
.Example AsciiDoc: A definition list explaining user-replaced values

[source,yaml,subs="+attributes,+quotes"]
----
cat <<EOF | oc -n <my_product_namespace> create -f -
apiVersion: v1
kind: Secret
metadata:
 name: <my_product_database_certificates_secrets> 
type: Opaque
stringData:
 postgres-ca.pem: |-
  -----BEGIN CERTIFICATE-----
  <ca_certificate_key> 
 postgres-key.key: |-
  -----BEGIN CERTIFICATE-----
  <tls_private_key> 
 postgres-crt.pem: |-
  -----BEGIN CERTIFICATE-----
  <tls_certificate_key> 
  # ...
EOF
----
+
where:

`<my_product_database_certificates_secrets>`:: Specifies the name of the certificate secret.
`<ca_certificate_key>`:: Specifies the CA certificate key.
`<tls_private_key>`:: Specifies the TLS private key.
`<tls_certificate_key>`:: Specifies the TLS certificate key.

* Use the appropriate admonition style to add notes pertaining to a code block, as described in xref:admonitions[]. 

[[date-formats]]
== Date formats

Follow the _IBM Style_ guide advice of _day Month year_ for date formats, for example, 3 October 2019.

When the format _day Month year_ causes a presentation or clarity issue, use _Month day, year_ (for example, October 3, 2019) instead.

[[man-pages]]
== Man page references

When referencing a man page in an "Additional resources" section, use the following format:

* `_<man_page_name>_(_<section_number>_)` man page on your system

Do not link to a website that contains the man page information. The contents of a man page might vary between systems or package versions, so users must run the `man` command on the target system to view the system-specific information for the named command or utility.

.Example: Single man page

* `sudoers(5)` man page on your system

.Example: Multiple man pages

* `nmcli(1)`, `nm-settings(5)`, and `sudoers(5)` man pages on your system

[[non-breaking-spaces]]
== Non-breaking spaces

Use a _non-breaking space_ (`+{nbsp}+`) between the words "Red" and "Hat". The non-breaking space prevents an automatic line break from separating the two words onto two lines.
A _non-breaking space_ prevents the company name from splitting across a line break.

.Example AsciiDoc: Non-breaking space
----
Before you begin to customize the installer, download the Red{nbsp}Hat-provided boot images.
----

[[product-names-versions-ref]]
== Product names and version references

Use attributes instead of hard-coded references when you refer to the name of your product in full, to its abbreviated form, or to its major or minor version.
Only use hard-coded version references if the version that you are referring to in a particular case never changes.

=== Attribute file

Define attributes for product name and product version and store them in a dedicated attributes file for each set of product documentation.
For examples of where you can store the shared attributes file inside your documentation repository, see the link:https://github.com/redhat-documentation/modular-docs/blob/mod-doc-repo-example/_artifacts/document-attributes.adoc[Example modular documentation repository].
Include the attributes file at the beginning of the `master.adoc` files of all titles in your documentation set:

.Example AsciiDoc: Attribute file included in a master.adoc file
[subs="+quotes"]
----
\include::__<path_to_directory_with_attributes_file>__/attributes.adoc[]
----

=== Minimum required attributes

Define attributes for the following values in each documentation set.
Note that the attribute names used in this section are only meant as examples.
You can use different attribute names:

The name of the product:: Use the product name attribute for all instances of the product name where possible.
Avoid using hard-coded product names.
For example:
+
.Example AsciiDoc: Product name attribute
----
:name-product: Red{nbsp}Hat JBoss Enterprise Application Platform
----

The abbreviated form of the product name:: If it is necessary for your product, you can use an attribute to store a shortened version of the name of your product, for example:
+
.Example AsciiDoc: Abbreviated product name attribute
----
:name-product-abbreviated: JBoss EAP
----

The major and minor version of the product:: Use an attribute for the product version in cases where the product version can change with each release and the content is still correct.
For example:
+
.Example AsciiDoc: Product version attributes
----
:version-product-minor: 1.11
:version-product-patch: 1.11.6
----
+
[NOTE]
====
Do not use the product version attribute if the version should not change.
For example, if a feature was introduced in a certain version, the version should be hard-coded.
====

You might create additional attributes according to what your documentation requires.
For example, you might combine existing product name attributes to create compound names of products or components:

.Example attributes for compound names of product components
----
:name-runtime-spring-boot: Spring Boot
:name-runtime-vertx: Eclipse Vert.x
:name-spring-reactive: {name-runtime-spring-boot} with {name-runtime-vertx} reactive components
----

[[single-step-procedures]]
== Single-step procedures

When a procedure contains only one step, use an unnumbered bullet.

For example:
====
* Install the `dnf-automatic` package.
====

[[titles-and-headings]]
== Titles and headings

Write all titles and headings, including the titles of product documentation guides and Knowledgebase articles, in sentence-style capitalization. Do not use headline-style capitalization.

.Examples
* _Composing a customized RHEL system image_
* _Configuring the node port service range_
* _How to perform an unsupported conversion from a RHEL-derived Linux distribution to RHEL_


[[user-replaced-values]]
== User-replaced values

A _user-replaced value_, also known as a replaceable or variable value, is a placeholder that the user replaces with a value that is relevant for their situation. User-replaced values are often found in places such as code blocks, file paths, and commands.

Use descriptive names for user-replaced values and follow this general format: _<value_name>_.

[NOTE]
====
For XML code blocks, see the guidance on xref:#user-replaced-values-xml[user-replaced values for XML].
====

Ensure that user-replaced values have the following characteristics:

* Surrounded by angle brackets (`< >`)
* Separated by underscores (`_`) for multi-word values
* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme
* Italicized
* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value
* If you want to use a user-replaced value in example output, format the replaceable value with italics and in angle brackets. Alternatively, if you choose to use an example value instead, do not italicize the example value and do not place it in angle brackets.

.Example AsciiDoc: User-replaced value in a paragraph

----
Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.
----

This example renders as follows in HTML:

====
Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.
====

To italicize a user-replaced value in a code block, you must add an attribute to apply text formatting, such as `subs="+quotes"` or `subs="normal"`, to the attribute list of the code block.

.Example AsciiDoc: User-replaced value in a code block

  [subs="+quotes"]
  ----
  $ *oc describe node __<node_name>__*
  ----

This example renders as follows in HTML:

====
[subs="+quotes"]
----
$ *oc describe node __<node_name>__*
----
====

.Example AsciiDoc: User-replaced value in an output example

  [subs="+quotes"]
  ----
  connection.id:              __<profile_name>__
  connection.uuid:            b6cdfa1c-e4ad-46e5-af8b-a75f06b79f76
  connection.type:            802-3-ethernet
  connection.interface-name:  enp7s0
  ----

This example renders as follows in HTML:

====
[subs="+quotes"]
----
connection.id:              __<profile_name>__
connection.uuid:            b6cdfa1c-e4ad-46e5-af8b-a75f06b79f76
connection.type:            802-3-ethernet
connection.interface-name:  enp7s0
----
====

To explain user-replaced values used in a code block, you must use a definition list following the code block. See xref:explain-commands-variables-in-code-blocks[] for details.


[[user-replaced-values-xml]]
== User-replaced values for XML

Because XML uses angle brackets (`< >`), the xref:#user-replaced-values[default guidance] for user-replaced values does not work well for it. If you are using user-replaced values in an XML code block, use the following format: _${value_name}_.

Ensure that user-replaced values in XML have the following characteristics:

* Surrounded by curly braces and preceded by a dollar sign (`${ }`)
* Separated by underscores (`_`) for multi-word values
* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme
* Italicized
* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value

.Example AsciiDoc: User-replaced value for an XML element

  [source,xml,subs="+quotes"]
  ----
  <ipAddress>__${ip_address}__</ipAddress>
  ----

This example renders as follows in HTML:

====
[source,xml,subs="+quotes"]
----
<ipAddress>__${ip_address}__</ipAddress>
----
====

.Example AsciiDoc: User-replaced value for an XML attribute

  [source,xml,subs="+quotes"]
  ----
  <oauth2-introspection client-id="__${client_id}__"/>
  ----

This example renders as follows in HTML:

====
[source,xml,subs="+quotes"]
----
<oauth2-introspection client-id="__${client_id}__"/>
----
====

To explain user-replaced values used in a code block, you must use a definition list following the code block. See xref:explain-commands-variables-in-code-blocks[] for details.



// TODO: Add new style entries alphabetically in this file
