
[[general-formatting]]
= General formatting

[[date-formats]]
== Date formats

Follow _The IBM Style Guide_  guidance of _day Month year_ for date formats, for example, 3 October 2019.

When the format _day Month year_ causes a presentation or clarity issue, use _Month day, year_ (for example, October 3, 2019) instead.


[[user-replaced-values]]
== User-replaced values

A _user-replaced value_ is a value that the user must replace with a value that is relevant for their situation. User-replaced values are often found in places such as code blocks, file paths, and commands.

Use descriptive names for user-replaced values and follow this general format: _<value_name>_.

Ensure that user-replaced values have the following characteristics:

* Surrounded by angle brackets (`< >`)
* Separated by underscores (`_`) for multi-word values
* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme
* Italicized
* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value.

.Example AsciiDoc: User-replaced value in a paragraph

----
Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.
----

This renders as:

====
Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.
====

To italicize a user-replaced value in a code block, you must add an attribute to apply text formatting, such as `subs="+quotes"` or `subs="normal"`, to the attribute list of the code block.

.Example AsciiDoc: User-replaced value in a code block

  [subs="+quotes"]
  ----
  $ oc describe node __<node_name>__
  ----

This renders as:

====
[subs="+quotes"]
----
$ oc describe node __<node_name>__
----
====

// TODO: In the future, add alternative guidance for XML

[[lead-in-sentences]]
== Lead-in sentences for `Prerequisites` and `Procedure` sections

A lead-in sentence in this context is the text that directly follows a `Prerequisites` or `Procedure` heading in a task-based module. It is distinct from the module abstract, which describes the goals of the user for the module.

Do not use a lead-in sentence in the `Prerequisites` or `Procedure` sections of a module unless it is necessary to aid navigation or add clarity.

The following examples demonstrate when a lead-in sentence might add value.

* Your module has a long list of prerequisites, and you want to group the prerequisties in sections to make it easier for users to understand what tasks must be performed to complete a procedure.
* Your module has a complex procedure or set of prerequisites, and you want to emphasize that all steps or prerequisites must be completed.

Use a complete sentence for the lead-in sentence to reduce ambiguity and support translation.

[[admonitions]]
== Admonitions

Admonitions should draw the reader’s attention to certain information. Keep admonitions to a minimum, and avoid placing multiple admonitions close to one another. If multiple admonitions are necessary, restructure the information by moving the less-important statements into the flow of the main content.

Valid admonition types:

- NOTE
- IMPORTANT
- WARNING
- TIP

[IMPORTANT]
====
CAUTION, which is another type of AsciiDoc admonition, is not fully supported by the Red Hat Customer Portal. Do not use this admonition type.
====

Admonitions should be short and concise. Do not include procedures in an admonition.

Only individual admonitions are allowed, for example, you cannot have a plural *NOTES* heading.

.Example AsciiDoc
----
[NOTE]
====
Text for note.
====
----

[product-names-versions-ref]]
== Product names and version references

Whenever you refer to the name of your product in full, or in its abbreviated form, or when you refer to the major and minor version of your product, avoid using hard-coded references and use attributes instead.
Only use hard-coded version references if the version that you are referring to in a particular case never changes.

=== Attribute file

Define attributes for product name and product version and store them in a dedicated attributes file for each set of product documentation.
For examples of where you can store the shared attributes file inside your documentation repository, see the link:https://github.com/redhat-documentation/modular-docs/tree/mod-doc-repo-example[Example modular documentation repository].
Include the attributes file at the beginning of the `master.adoc` files of all titles in your documentation set:

.master.adoc
[source,asciidoc,options="nowrap"]
----
\include::<path-to-directory-with-attributes-file>/attributes.adoc[]
----

=== Minimum required attributes

Define attributes for the following values in each documentation set.
Note that the attribute names used in this section are only meant as examples.
You can use different attribute names:

The name of the product:: Use the product name attribute for all instances of the product name where possible.
Avoid using hard-coded product names.
For example:
+
.Example product name attribute
----
:name-product: Red Hat build of Quarkus
----

The abbreviated form of the product name:: If it is necessary for your product, you can use an attribute to store a shortened version of the name of your product, for example:
+
.Example abbreviated product name attribute
----
:name-product-abbreviated: RHBQ
----

The major and minor version of the product:: Use an attribute for the product version in cases where the product version can change with each release and the content is still correct.
For example:
+
.Example long and short product version attributes
----
:version-product-short: 1.11.6
:version-product-long: 1.11
----
+
[NOTE]
====
Do not use the product version attribute if the version should not change.
For example, if a feature was introduced in a certain version, the version should be hard-coded.
====

You might create additional attributes according to what your documentation requires.
For example, you might combine existing product name attributes to create compound names of products or components:

.Example attributes for compound names of product components
----
:name-runtime-spring-boot: Spring Boot
:name-runtime-vertx: Eclipse Vert.x
:name-spring-reactive: {name-runtime-spring-boot} with {name-runtime-vertx} reactive components
----
