
[[general-formatting]]
= General formatting

[[date-formats]]
== Date formats

Follow _The IBM Style Guide_  guidance of _day Month year_ for date formats, for example 3 October 2019.

When the format _day Month year_ causes a presentation or clarity issue, use instead: _Month day, year_ (for example, October 3, 2019).


[[user-replaced-variables]]
== User-replaced variables

[[lead-in-sentences]]
== Lead-in sentences for `Prerequisites` and `Procedure` sections

A lead-in sentence in this context is the text that directly follows a `Prerequisites` or `Procedure` heading in a task-based module. It is distinct from the module abstract, which describes the goals of the user for the module.

Do not use a lead-in sentence in the `Prerequisites` or `Procedure` sections of a module unless it is necessary to aid in navigation or add clarity.

The following are examples of when a lead-in sentence might add value:

* Your module has a very long list of prerequisites, and you want to sectionalize the prerequisties to make it easier for users to understand what tasks must be completed to succesfully complete a proceudre.
* Your module has a complex procedure or set of prerequisites, and you want to emphasize that all steps or prerequisites must be completed.

Use a complete sentence for the lead-in sentence, to reduce ambiguity and support translation.

[[admonitions]]
== Admonitions

Admonitions should draw the reader’s attention to certain information. Keep admonitions to a minimum, and avoid placing multiple admonitions in close proximity to one another. If multiple admonitions are necessary, restructure the information by removing the less important statements and placing them into the flow of the main content.

Valid admonition types:

- NOTE
- IMPORTANT
- WARNING
- TIP

[IMPORTANT]
====
CAUTION, which is another type of AsciiDoc admonition, is not fully supported by the Red Hat Customer Portal. Do not use this admonition type.
====

Admonitions should be short and concise. Do not include procedures in an admonition.

Only individual admonitions are allowed. For example, you cannot have a plural *NOTES* heading.

.Example AsciiDoc
----
[NOTE]
====
Text for note.
====
----

// [[product-names-versions-ref]]
// == Product names and version references
