
[[general-formatting]]
= General formatting

[[date-formats]]
== Date formats

Follow _The IBM Style Guide_  guidance of _day Month year_ for date formats, for example 3 October 2019.

When the format _day Month year_ causes a presentation or clarity issue, use instead: _Month day, year_ (for example, October 3, 2019).


[[user-replaced-variables]]
== User-replaced variables

[[lead-in-sentences]]
== Lead-in sentences for `Prerequisites` and `Procedure` sections

A lead-in sentence in this context is the text that directly follows a `Prerequistes` or `Procedure` heading in a task-based module. It is distinct from the module abstract, which describes the goals of the user for the module.

Avoid using a lead-in sentence in the `Prerequisites` or `Procedure` sections of a module if it does not add value. Use a lead-in sentence to introduce a procedure or prerequisite only in instances where the lead-in sentence adds context and makes it easier for the user to understand the module content. Use a complete sentence for the lead-in sentence, to reduce ambiguity and support translation for international audiences. 


Example lead-in sentence
----
.Prerequisite

Before registering it to Satellite Server, ensure that the base system on which you want to install Capsule meets the following conditions:

* On Satellite Server, a manifest must be installed and it must contain the appropriate repositories for the organization you want Capsule to belong to.
* The manifest must contain repositories for the base system on which you want to install Capsule, as well as any clients that you want to connect to Capsule.
* The repositories must be synchronized.
* For more information on manifests and repositories, see Managing Subscriptions in the Red Hat Satellite Content Management Guide.

.Procedure
----



[[admonitions]]
== Admonitions

Admonitions should draw the reader’s attention to certain information. Keep admonitions to a minimum, and avoid placing multiple admonitions in close proximity to one another. If multiple admonitions are necessary, restructure the information by removing the less important statements and placing them into the flow of the main content.

Valid admonition types:

- NOTE
- IMPORTANT
- WARNING
- TIP

[IMPORTANT]
====
CAUTION, which is another type of AsciiDoc admonition, is not fully supported by the Red Hat Customer Portal. Do not use this admonition type.
====

Admonitions should be short and concise. Do not include procedures in an admonition.

Only individual admonitions are allowed. For example, you cannot have a plural *NOTES* heading.

.Example AsciiDoc
----
[NOTE]
====
Text for note.
====
----

// [[product-names-versions-ref]]
// == Product names and version references
