
[[graphical-interfaces]]
= Graphical interfaces

For more detailed guidance on how to document user interface (UI) elements, see link:https://www.patternfly.org/v4/ux-writing/about[PatternFly].

[[microcopy]]
== Microcopy

The words in a user interface, commonly referred to as "UX copy" or "microcopy", are just as important as the components or layouts. Microcopy is another element of design, and it can drive better UX decisions and guide users to succeed. Red{nbsp}Hat cloud services are based on PatternFly, an open source design system created to enable consistency and usability across a wide range of applications and use cases.

See link:https://www.patternfly.org/v4/ux-writing/about[UX writing] in the PatternFly content style guide for comprehensive guidelines about documenting user interfaces.

[[screenshots]]
== Screenshots

Avoid screenshots for both accessibility and localization reasons. If you must use screenshots, use them as judiciously as possible and ensure alt text is unique and descriptive. For more information about proper use of images in user interface documentation, see xref:accessibility[Accessibility].

[[text-entry]]
== Text entry

To indicate that a user should input text, use "enter" as opposed to "type" or "input". The text to enter should be in monospace.

.Example AsciiDoc
----
In the *Name* field, enter `test-postgresql`.
----

[[user-interface-elements]]
== User interface elements

Use bold text for all graphical user interface (GUI) element names, including menus, menu items, buttons, dialog boxes, and windows. Use bold text for the element name if the name appears in the GUI, even if the element is not clickable.

.Example AsciiDoc
----
On the *Installed Operators* page, click *Metering*.
----

If an element is not labeled in the GUI, refer to the element by a generic description and do not use bold text. For example, if a search field is not labeled in the GUI, write it as "the search field", not "the *Search* field".




// TODO: Add new style entries alphabetically in this file
