
[[links]]
= Links

[[cross-references]]
== Cross-references

Follow these guidelines when adding cross-references within your documentation:

* Include cross-references only when necessary.
* If the information is critical, consider including it instead of cross-referencing.

.Example AsciiDoc: Cross-reference
----
For more information about <topic>, see xref:<link>[<link_text>].
----

[[external-links]]
== External links

Follow these guidelines when linking externally:

* Avoid unnecessary links to external sites not owned and operated by Red{nbsp}Hat or IBM.
Links to external sites can change or be unreliable.
In addition, customers might infer that Red{nbsp}Hat endorses or supports the linked content, even if that is not the intent.
+
[NOTE]
====
Links to upstream sites, such as GitHub, are considered to be external links.
====
+
* When possible, link to a top-level page and avoid deep links to a specific page or image.
Deep links can break more frequently and can inadvertently bypass a site's legal notices.
* Do not use bare URLs for links.
Bare URLs are unhelpful because they do not provide adequate context about the link target.
* Do not use URL shorteners to replace full URLs.
* Always include meaningful link text.
Meaningful link text describes to users what content they will see if they click the link.
* Use hyperlinks unless the URL is an example URL or is otherwise inaccessible to users.
* By default, links are followable and crawlable. Do not use the `nofollow` link option unless absolutely necessary.

For information about links and web addresses, including using URLs in examples, see the _IBM Style_ guide.

.Example AsciiDoc: External link
----
For more information about <topic>, see link:<link>[<link_text>].
----

[[link-text]]
== Link text

Follow these guidelines when specifying link text:

* Contextually describe what the user will find at the target location so that they can decide if they want to leave their current location.
* Use a concise sentence or sentence fragment as the link text.
* Avoid irrelevant link text.

[[rh-kb-links]]
== Links to Red{nbsp}Hat Knowledgebase articles

* Use the title of the Knowledgebase article for the link text, or use descriptive running text.
* When not using running text, call out that this is a Knowledgebase article.
* When the link appears in *Additional resources*, put the article title first, followed by `(Red{nbsp}Hat Knowledgebase)`.

.Example: Article title

For a non-cloud environment, you can resize the disk and file system. For more information, see the Red{nbsp}Hat Knowledgebase solution link:https://access.redhat.com/solutions/199573[Does RHEL 7 support online resize of disk partitions?].

.Example: Running text

If your Apache web server configuration enables SSL security, verify that you enable only the TLSv1 protocol and disable SSLv2 and SSLv3. This is because of the link:https://access.redhat.com/solutions/1232413[POODLE SSL vulnerability (CVE-2014-3566)].

.Example: Additional resources

* link:https://access.redhat.com/solutions/199573[Does RHEL 7 support online resize of disk partitions?] (Red{nbsp}Hat Knowledgebase)

// TODO: Add new style entries alphabetically in this file
