
[[links]]
= Links

The following guidelines improve findability and search engine optimization.

.Technical best practices

* Use hyperlinks consistently.
* Do not use non hyperlinks.
* Do not use JavaScript links. 
* Do not use Flash Links.
* Do not use links in Frames or iframes.
* Default to followable, crawlable links. Do not use “nofollow” links unless absolutely necessary.
* Include links only when necessary.

.Link text best practices

* Contextually describe what the user will find at the target location so that they can decide if they want to leave their current location. 
* Avoid irrelevant link text.
* You can use a sentence or sentence fragment as the link text.



[[internal-links]]
== Internal links

Internal links are links within www.redhat.com.

You can use one of the following example link structures for consistency.

.Example AsciiDoc for internal links
----
For more information about <topic>, see xref:<link>[<link_text>].
----

To link to a separate user story:
----
For more information about <topic>, see link:<link>[<link_text>] in _<title_name>_.
----


[[external-links]]
== External links

External links are links to a domain other than www.redhat.com.

You can use the following example link structure for consistency.

.Example AsciiDoc for external links
----
For more information about <topic>, see link:<link>[<link_text>].
----

