
[[links]]
= Links

[[cross-references]]
== Cross-references

Follow these guidelines when adding cross-references within your documentation:

* Include cross-references only when necessary.
* If the information is critical, consider including it instead of cross-referencing.

.Example AsciiDoc: Cross-reference
----
For more information about <topic>, see xref:<link>[<link_text>].
----

[[external-links]]
== External links

Follow these guidelines when linking externally:

* Always include link text. Bare URLs (URLs without explanatory information) are unhelpful because they do not provide adequate context about the link target.
* Use hyperlinks unless the URL is an example URL or is otherwise inaccessible to users. See the _IBM Style_ guide for information about using addresses in examples.
* By default, links are followable and crawlable. Do not use the "nofollow" link option unless absolutely necessary.
* Avoid links to external sites when possible. External links can change or be unreliable.
* Avoid deep links (to a specific page or image from another company) to prevent an ongoing maintenance responsibility and to prevent bypassing a website's legal information.

.Example AsciiDoc: External link
----
For more information about <topic>, see link:<link>[<link_text>].
----

[[link-text]]
== Link text

Follow these guidelines when specifying link text:

* Contextually describe what the user will find at the target location so that they can decide if they want to leave their current location.
* Use a concise sentence or sentence fragment as the link text.
* Avoid irrelevant link text.

[[rh-kb-links]]
== Links to Red Hat Knowledgebase articles

* Use the title of the Knowledgebase article for the link text, or use descriptive running text.
* Call out that this is a Knowledgebase article when _not_ using running text.
* When the link appears in *Additional resources*, put the article title first, followed by `(Red Hat Knowledgebase)`.


.Example: Article title

For a non-cloud environment, you can resize the disk and file system. For more information, see the Red Hat Knowledgebase solution link:https://access.redhat.com/solutions/199573[Does RHEL 7 support online resize of disk partitions?].

.Example: Running text

If your Apache web server configuration enables SSL security, verify that you enable only the TLSv1 protocol and disable SSLv2 and SSLv3. This is because of the link:https://access.redhat.com/solutions/1232413[POODLE SSL vulnerability (CVE-2014-3566)].

.Example: Additional resources

* link:https://access.redhat.com/solutions/199573[Does RHEL 7 support online resize of disk partitions?] (Red Hat Knowledgebase)

// TODO: Add new style entries alphabetically in this file
