[[cloud-services]]
= Cloud services guidelines

Cloud services are applications that run on a platform backed by data storage infrastructure and are hosted and managed by Red Hat on behalf of the customer. Cloud services provide rapid iteration and can more quickly deliver updated product functionality.

This means a product is no longer running exclusively in the customer’s infrastructure but is a service running in the cloud that is operated and maintained by Red Hat. Red Hat is now responsible for ensuring the service is secure, scalable, performant, and available at all times.

Cloud services documentation requires a shift from how documentation is typically created for an on-premise product. There is more emphasis on the content delivered within the product's user interface itself, a need to deliver content rapidly without having a set release cadence, and to adapt content to the needs of cloud service users. For example, there might not be a need for upgrade and migration content that’s typical for on-premise products.

This section provides guidelines for creating content for the user interface, emphasizing accessibility, with the intent to provide consistency in how users understand and navigate across different cloud services.

[[accessibility]]
== Accessibility

Ensure that documentation meets Section 508 compliance for accessibility. Accessibility standards are derived from the link:https://www.w3.org/TR/WCAG20/[Web Content Accessibility Guidelines (WCAGA)] and the link:https://www.access-board.gov/ict/[ICT Accessibility 508 Standards and 255 Guidelines].

[[cloud-services-images]]
=== Images

Use text equivalents for every diagram, image, or other non-text element. Avoid using images of text instead of actual text.

Evaluation:

* All icons, images, diagrams, and non-text elements that convey information must have meaningful alternative-text descriptions.
** For icons, use alternative text that describes what the icon does rather than what it looks like. For example, the alt text for a `+` icon is "Add" rather than "Plus Sign".
* The document is free from images of text; for example, a screen capture image of an informational table. Make sure that actual text is used to convey information, rather than images of text.

[[cloud-services-links-hypertext]]
=== Links and hypertext

The purpose of each link can be determined from the link text alone, or from the link text together with the link context. Links must lead to the correct target locations within the document, or to a valid external web page location. Ensure that all links work as expected.

* All link URLs and cross-reference links must provide descriptive text that conveys information about the content of the target linked page prior to clicking the link. Do not use a generic phrase like “click here”.

Examples:

* A link to a different section in the same document shows the section title.
* An external link provides the site name or title of the target web page.
* URLs must link to correct and valid web destinations.

[[cloud-services-tables]]
=== Tables

When working with tables, accessibility tools such as a screen reader can programmatically determine the location of the content in each row and column. Screen readers interact with a data table based on the number of columns and rows, and provide table navigation to the user by reading row and column headers in the order they occur.

* All tables must have a simple, logical reading order from left to right, top to bottom.
* Avoid tables with irregular headers. Tables with multi-level headers, or spanned rows and cells, do not provide a clear horizontal or vertical association between header and data cells, and are too complex for accessibility tools to interpret.
** See the example in link:https://www.w3.org/WAI/tutorials/tables/irregular/[Tables with irregular headers].
* Avoid blank header cells. Older screen readers often do not handle blank header cells correctly. Simplify tables to remove empty header cells, or add row and column text to each header cell.
* For more information on adding titles using AsciiDoc, see link:https://docs.AsciiDoctor.org/AsciiDoc/latest/tables/add-title/[Add a Title to a Table].

[[cloud-services-visual-info]]
=== Colors and other visual information


Color should not be used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element. The documentation interface must provide at least one visual mode of operation that does not require user perception of color.
Avoid indicating direction, such as left, right, above and below, since these have no meaning to a screen reader. Instructions provided for understanding and operating the product must not rely solely on sensory characteristics such as shape, size, visual location, or orientation.

* Avoid instructions that rely solely on sensory characteristics.
* Information that is conveyed by color differences must also be provided in text form.
* For images or diagrams in your document, ensure sufficient contrast between foreground and background text or graphical elements. Graphics and diagrams in your document produced by a CCS graphic designer meet contrast ratio requirements. If you created a graphic or diagram yourself, use the WCAG reference for link:https://www.w3.org/TR/WCAG21/#contrast-minimum[Contrast], and the link:https://webaim.org/resources/contrastchecker/[Contrast Checker] to evaluate contrast compliance.
* Avoid directional indicators such as left, right, above and below when providing navigational instruction in the user interface.

[[html-meaningful-sequence]]
=== Well-formed HTML and meaningful sequence

The meaning of content relies on the order in which you present it. For example, English content is arranged from left to right and readers usually look at a left-hand column before a right-hand column. Users who rely on assistive technology (such as a screen reader) to interpret content need the content to be presented in a meaningful order. If content is presented out of sequence, readers might become disoriented and unable to understand the content.

* Correctly nest headings from H1 to H2, H3 and so forth to indicate relative importance. Do not skip heading levels.
* Use correct AsciiDoc tags to produce the intended HTML.


.Additional resources

*  Understanding WCAG 2.0
** link:https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv.html[Text Alternatives]
** link:https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-text-presentation.html[Images of Text]
** link:https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html[Link Purpose (In Context)]
** link:https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-understanding.html[Sensory Characteristics]
** link:https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html[Use of Color]
** link:https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html[Meaningful Sequence]
* link:https://webaim.org/resources/contrastchecker/[WebAIM Contrast Checker]

[[localization]]
== Localization

Documentation that follows the _IBM Style_ guide for fairly conversational tone does not present issues with human or machine translation and better aligns with tone in the user interface. Use contractions where appropriate.

[[microcopy]]
== Microcopy

The words in a user interface, commonly referred to as "UX copy" or "microcopy," are just as important as the components or layouts. UX copy is another element of design, and it can drive better UX decisions and guide users to succeed. Red Hat cloud services are based on Patternfly, an open source design system created to enable consistency and usability across a wide range of applications and use cases.

See link:https://www.patternfly.org/v4/ux-writing/about[UX writing] in the Patternfly content style guide for comprehensive guidelines when writing for the user interface.

[[screenshots]]
== Screenshots
Avoid screenshots for both accessibility and localization reasons. If you must use screenshots use them as judiciously as possible and ensure alt text is unique and descriptive. See xref:accessibility[Accessibility] for more information on proper use of images in user interface documentation.

/////
TBD as more information is provided on unique content types.

[[service-defintion]]
== Service definition


[[topics-assemblies]]
== Topics and assemblies
/////
