[[release-notes]]
= Release notes

A release note explains specific product behavior, capability, or problem relevant to a product version. Release notes for a particular product version are collected in a document that is published when the new version is released.

[[style-advice-for-release-note-texts]]
== Style advice for release note texts

The normal stylistic guidelines for documentation from the _IBM Style_ guide and the _ Red Hat supplementary style guide for product documentation_ apply also to release note texts, particularly the following:

* When you first mention a utility, package, command, or similar item outside of a heading, define it. Do not assume that the customer is familiar with it. 
** Omit the definition in later occurrences. If the context is ambiguous, for example, when the release note text mentions both an `example` package and an `example` service, you can repeat the definition to add clarity.
** Avoid definitions in headings, but you can use them to disambiguate different meanings of the same name.
* Do not start a sentence with a word in lowercase. You can repeat a definition to avoid starting a sentence with a lowercase name. See: link:https://www.ibm.com/docs/en/ibm-style?topic=grammar-capitalization#general-text[Capitalization (IBM Style)].
* Expand abbreviations in descriptions. Do not expand abbreviations in headings. See: link:https://www.ibm.com/docs/en/ibm-style?topic=grammar-abbreviations[Abbreviations (IBM Style)].
* When comparing versions, use "later" and "earlier" instead of "newer" and "older". See: link:https://www.ibm.com/docs/en/ibm-style?topic=word-usage#later[Later (IBM Style)].
* Avoid complicated syntax, such as passive voice and modal verbs, and ambiguous language. For example, replace "Should XY happen" with "If XY happens".
* Keep admonitions to a minimum, and avoid placing multiple admonitions in a single note. Do not begin a release note with an admonition. See xref:admonitions[Admonitions (Red Hat supplementary style guide)].
* Avoid using telegraphic language common in merge requests and changelogs, for example, "Remove deprecated support macros".

[[tenses-in-release-notes]]
== Tenses in release notes

Write the release notes from the perspective of just after the release, which is when most of the customers will read them. The state before the update is in the past, the state after the update is in the present, any future updates are in the future.

* Use the *simple present tense* as much as possible.
* Do not use *future tenses* (or "should" or "might") to describe the state after the update. You can use future tenses to refer to future releases.
* Use the *simple past tense* to describe the previous situation before the current update.
* You can use the *present perfect tense* to describe the current update. “With this update, the X component has been removed from the Y package.”
* Follow the CCFR (Cause-Consequence-Fix-Result) tense logic in bug fixes.
* Do not use “now” to refer to the state after the update. See: xref::now[Now (RH SSG)].

[[headings-for-release-notes]]
== Headings for release notes

Introduce each release note with a heading that summarizes the release note. This practice helps customers to quickly determine if the release note is relevant to them.

* The heading can, but does not need to be, a full sentence. Do not use a period at the end of the heading.
* Use _Sentence-style capitalization_ (not _Title Case_). Headings can start with a lowercase letter (such as with a lowercase name of a component).
+
----
.`start` does not start the computer when `donotstop` is stopped
----

* Keep the heading under 120 characters. Write headings that are informative and specific without being overly long or too short:
** Follow the specifics for the release notes category.
** Mention the component in a heading whenever it might not be obvious.
** Be specific; do not over-generalize headings (“Program no longer crashes” or “Program is no longer vulnerable” are over-generalized).

* Do not expand abbreviations in headings.
* Do not use definitions in headings unless necessary for clarity.
* Do not start the heading with a gerund. Use gerunds only for procedural content. See: link:https://www.ibm.com/docs/en/ibm-style?topic=format-headings[Headings (IBM Style)].

== Release note categories

You can write doc texts in more than one way, depending on the issue type:

* Enhancement
* Bug fix
* Known issue
* Technology Preview
* Deprecated functionality

Use the following general structure for consistency.

=== Enhancement

Use present tense in one of the following formats:
----
This enhancement <present tense explanation>.
----
----
With this update, <present tense explanation>.
----
.Example doc texts
----
This enhancement optimizes migration of an RBD volume from one Cinder back end to another when the volume resides within the same Ceph cluster. If both volumes are in the same Ceph cluster, Ceph performs data migration instead of the cinder-volume process. This reduces migration time.
----
----
With this update, you can create application credentials to use keystone to authenticate applications.
----

=== Bug fix

Use past tense for the problem and present tense for the solution, in the following format:
----
Before this update,  <X problem> caused <Y situation> (OPTIONAL: under the following <Z conditions>). With this update, <fix> resolves the issue (OPTIONAL: and <agent> can <perform operation> successfully).
----
.Example doc text
----
Before this update, the loopback device for Cinder iSCSI/LVM backend was not re-created after a system restart, which prevented the cinder-volume service from restarting. With this update, a systemd service re-creates the loopback device and the Cinder iSCSI/LVM backend persists after a restart.
----

=== Known issue

Use present tense for the issue and the imperative form for the workaround in the following format:
----
There is currently a known issue <present tense explanation> under <X conditions>.

Workaround: <workaround>.
----
.Example doc text
----
Currently, you cannot use Orchestration (heat) templates with the director to deploy an overcloud that requires NFS as an Image service (glance) back end. There is currently no workaround for this issue.
----
----
The Compute services (nova) might fail to deploy because the `nova_wait_for_compute_service` script is unable to query the Nova API. If a remote container image registry is used outside of the undercloud, the Nova API service might not finish deploying in time.
Workaround: Rerun the deployment command, or use a local container image registry on the undercloud.
----

=== Technology Preview

For guidance and the template text to use for Technology Preview features, see the xref:technology-preview-guidance[Technology Preview] section.

[[deprecated-and-removed-features]]
=== Deprecated and removed features

Documenting the deprecation and removal stages of software features requires careful and precise communication.
Highlight the following stages to users:

* Plan to deprecate
* Deprecate
* Plan to remove
* Remove

When alternatives to or workarounds for deprecated features are available, clearly inform users about them.

==== Referring to releases in deprecation and removal notices
In general, avoid definitive statements about specific releases, release versions, or dates for deprecation or removal.
When possible, use the phrase "is planned for a future release" because it accounts for the possibility of changes to the planned deprecation or removal timeline.

If you must be specific about a release, use provisional language to reflect the fluid nature of development plans and to acknowledge the potential for plans to change.
For example, if you must cite a specific version, rather than stating "<x> will be deprecated in version 4.16", use "It is currently planned for <x> to be deprecated in version 4.16".
Alternatively, if you must cite a deprecation or removal timeline and you want to avoid citing a specific release number, use a phrase such as "<x> is planned to be deprecated in the next release".

==== Deprecation notice template
[subs="+quotes"]
----
In __<product_name> <release>__, __<name_of_capability_or_feature>__ is deprecated and is planned to be removed in the __<deprecation_timeline>__. Red{nbsp}Hat will provide bug fixes and support for this feature during the current release lifecycle, but this feature will no longer receive enhancements and will be removed. As an alternative to __<name_of_capability_or_feature>__, you can use __<alternative_capability_or_feature_if_available>__ instead.
----

.Example deprecation notice doc text
----
In Red{nbsp}Hat OpenStack Platform (RHOSP) 14, the director graphical user interface is deprecated and is planned to be removed in a future release. Red{nbsp}Hat will provide bug fixes and support for this feature during the current release lifecycle, but this feature will no longer receive enhancements and will be removed.
----

==== Removal notice template
[subs="+quotes"]
----
In __<product_name> <current_release>__, __<name of capability or feature>__ has been removed. Bug fixes and support are provided only through the end of the __<previous_release>__ lifecycle. As an alternative to __<name_of_capability_or_feature>__, you can use __<alternative_capability_or_feature_if_available>__ instead.
----
.Example removal notice doc text
----
In Red{nbsp}Hat OpenStack Platform (RHOSP) 16, the Data Processing service (sahara) has been removed. Bug fixes and support are provided only through the end of the RHOSP 15 lifecycle.
----


// TODO: Add new style entries alphabetically in this file
