[[release-notes]]
= Release notes

[[release-notes-doc-texts]]
== Release notes doc texts

A _doc text_ is a short description of an engineering Bugzilla or Jira issue that is published in product Errata advisories and release notes. Engineering typically supplies draft content, which is a summary of the issue, then technical writers edit or rewrite the draft content in accordance with the _IBM Style_ guide. You can write doc texts in more than one way, depending on the issue type:

* Enhancement
* Bug fix
* Known issue
* Technology Preview
* Deprecated functionality

Use the following general structure for consistency.

=== Enhancement

Use present tense in one of the following formats:
----
This enhancement <present tense explanation>.
----
----
With this update, <present tense explanation>.
----
.Example doc texts
----
This enhancement optimizes migration of an RBD volume from one Cinder back end to another when the volume resides within the same Ceph cluster. If both volumes are in the same Ceph cluster, Ceph performs data migration instead of the cinder-volume process. This reduces migration time.
----
----
With this update, you can create application credentials to use keystone to authenticate applications.
----

=== Bug fix

Use past tense for the problem and present tense for the solution, in the following format:
----
Before this update,  <X problem> caused <Y situation> (OPTIONAL: under the following <Z conditions>). With this update, <fix> resolves the issue (OPTIONAL: and <agent> can <perform operation> successfully).
----
.Example doc text
----
Before this update, the loopback device for Cinder iSCSI/LVM backend was not re-created after a system restart, which prevented the cinder-volume service from restarting. With this update, a systemd service re-creates the loopback device and the Cinder iSCSI/LVM backend persists after a restart.
----

=== Known issue

Use present tense for the issue and the imperative form for the workaround in the following format:
----
There is currently a known issue <present tense explanation> under <X conditions>.

Workaround: <workaround>.
----
.Example doc text
----
Currently, you cannot use Orchestration (heat) templates with the director to deploy an overcloud that requires NFS as an Image service (glance) back end. There is currently no workaround for this issue.
----
----
The Compute services (nova) might fail to deploy because the `nova_wait_for_compute_service` script is unable to query the Nova API. If a remote container image registry is used outside of the undercloud, the Nova API service might not finish deploying in time.
Workaround: Rerun the deployment command, or use a local container image registry on the undercloud.
----

=== Technology Preview

For guidance and the template text to use for Technology Preview features, see the xref:technology-preview-guidance[Technology Preview] section.

[[deprecated-and-removed-features]]
=== Deprecated and removed features

Documenting the deprecation and removal stages of software features requires careful and precise communication.
Highlight the following stages to users:

* Plan to deprecate
* Deprecate
* Plan to remove
* Remove

When alternatives to or workarounds for deprecated features are available, clearly inform users about them.

==== Referring to releases in deprecation and removal notices
In general, avoid definitive statements about specific releases, release versions, or dates for deprecation or removal.
When possible, use the phrase "is planned for a future release" because it accounts for the possibility of changes to the planned deprecation or removal timeline.

If you must be specific about a release, use provisional language to reflect the fluid nature of development plans and to acknowledge the potential for plans to change.
For example, if you must cite a specific version, rather than stating "<x> will be deprecated in version 4.16", use "It is currently planned for <x> to be deprecated in version 4.16".
Alternatively, if you must cite a deprecation or removal timeline and you want to avoid citing a specific release number, use a phrase such as "<x> is planned to be deprecated in the next release".

==== Deprecation notice template
[subs="+quotes"]
----
In __<product_name> <release>__, __<name_of_capability_or_feature>__ is deprecated and is planned to be removed in the __<deprecation_timeline>__. Red{nbsp}Hat will provide bug fixes and support for this feature during the current release lifecycle, but this feature will no longer receive enhancements and will be removed. As an alternative to __<name_of_capability_or_feature>__, you can use __<alternative_capability_or_feature_if_available>__ instead.
----

.Example deprecation notice doc text
----
In Red{nbsp}Hat OpenStack Platform (RHOSP) 14, the director graphical user interface is deprecated and is planned to be removed in a future release. Red{nbsp}Hat will provide bug fixes and support for this feature during the current release lifecycle, but this feature will no longer receive enhancements and will be removed.
----

==== Removal notice template
[subs="+quotes"]
----
In __<product_name> <current_release>__, __<name of capability or feature>__ has been removed. Bug fixes and support are provided only through the end of the __<previous_release>__ lifecycle. As an alternative to __<name_of_capability_or_feature>__, you can use __<alternative_capability_or_feature_if_available>__ instead.
----
.Example removal notice doc text
----
In Red{nbsp}Hat OpenStack Platform (RHOSP) 16, the Data Processing service (sahara) has been removed. Bug fixes and support are provided only through the end of the RHOSP 15 lifecycle.
----


// TODO: Add new style entries alphabetically in this file
