
[[specific-doc-types]]
= Specific documentation types

[[prerequisites]]
== Prerequisites

When writing prerequisites, be as clear and concise as possible. You can use the passive voice, _if necessary_, to achieve that end.

Write prerequisites as checks that are true or that the user must have completed before they begin a procedure. They can be actions that the user, another person, or piece of technology has completed. Prerequisites can also include items that the user must have ready before beginning the procedure.

* The passive voice might be appropriate for a prerequisite that is not completed by the current user. For example, having a configuration enabled by a system admin.

* Avoid using imperative formations.

* Use parallel language when writing prerequisites. For example, if one bullet is a complete sentence, the other bullets should be complete sentences. But one bullet could be passive voice and another active voice.

.Examples of prerequisites

* JDK 11 or later is installed.
+
Passive voice: the agent is unknown or unimportant.

* A running Kafka instance in {product}.

* You are logged in to the Administration Portal.

* You have validated Thing 1.

.Additional resources

* link:https://redhat-documentation.github.io/modular-docs/#creating-procedure-modules[_Procedure Prerequisites_ in the _Modular Documentation Reference Guide_]

[[release-notes]]
== Release notes

[[release-notes-doc-texts]]
=== Release notes doc texts

A _doc text_ is a short description of an engineering Bugzilla or Jira issue that is published in product Errata advisories and release notes. Engineering typically supplies draft content, which is a summary of the issue, then technical writers edit or rewrite the draft content in accordance with _The IBM Style Guide_. You can write doc texts in more than one way, depending on the issue type:

* Enhancement
* Bug fix
* Known issue
* Technology Preview
* Deprecated functionality

Use the following general structure for consistency.

[discrete]
==== Enhancement

Use present tense in one of the following formats:
----
This enhancement <present tense explanation>.
----
----
With this update, <present tense explanation>.
----
.Example doc texts
----
This enhancement optimizes migration of an RBD volume from one Cinder back end to another when the volume resides within the same Ceph cluster. If both volumes are in the same Ceph cluster, Ceph performs data migration instead of the cinder-volume process. This reduces migration time.
----
----
With this update, you can create application credentials to use keystone to authenticate applications.
----


[discrete]
==== Bug fix

Use past tense for the problem and present tense for the solution, in the following format:
----
Before this update,  <X problem> caused <Y situation> (OPTIONAL: under the following <Z conditions>). With this update, <fix> resolves the issue (OPTIONAL: and <agent> can <perform operation> successfully).
----
.Example doc text
----
Before this update, the loopback device for Cinder iSCSI/LVM backend was not recreated after a system restart, which prevented the cinder-volume service from restarting. With this update, a systemd service recreates the loopback device and the Cinder iSCSI/LVM backend persists after a restart.
----

[discrete]
==== Known issue

Use present tense for the issue and the imperative form for the workaround in the following format:
----
There is currently a known issue <present tense explanation> under <X conditions>.

Workaround: <workaround>.
----
.Example doc text
----
Currently, you cannot use Orchestration (heat) templates with the director to deploy an overcloud that requires NFS as an Image service (glance) back end. There is currently no workaround for this issue.
----
----
The Compute services (nova) might fail to deploy because the `nova_wait_for_compute_service` script is unable to query the Nova API. If a remote container image registry is used outside of the undercloud, the Nova API service might not finish deploying in time.
Workaround: Rerun the deployment command, or use a local container image registry on the undercloud.
----

[discrete]
==== Technology Preview

Use present tense in the following format:
----
In <release>, a Technology Preview is available for <feature explanation>.
----
.Example doc text
----
In Red Hat OpenStack Platform 16.0, a Technology Preview is available for the Bare Metal Provisioning service (ironic) deployed on an IPv6 provisioning network for BMaaS (Bare Metal as-a-Service) tenants.
----


[discrete]
==== Deprecated functionality
Warn users about the following deprecation stages:

* Plan to deprecate
* Deprecate
* Plan to remove
* Remove

If available, inform users of alternative capabilities and workarounds.

[discrete]
===== Deprecation notice
----
In <product> <release>, <name of capability> is deprecated. Bug fixes and support are provided through the end of the <releasename or, if unknown, “a future”> life cycle. After which, no new feature enhancements are made. (Optional: You can use <alternative capability> instead.)
----
.Example deprecation notice doc text
----
In Red Hat Openstack Platform (RHOSP) 14, the director graphical user interface is deprecated. Bug fixes and support is provided through the end of a future life cycle but Red Hat do not implement new feature enhancements.
----

[discrete]
===== Removal notice
----
In <product> <release>, <name of capability> is removed. Bug fixes and support is provided through the end of the <releasename or, if unknown, “a future”> life cycle. After which, no new feature enhancements are made. (Optional: You can use <alternative capability> instead.)
----
.Example removal notice doc text
----
In Red Hat OpenStack Platform (RHOSP) 16, the Data Processing service (sahara) is removed. Bug fixes and support are provided through the end of the RHOSP 15 life cycle but Red Hat do not implement new feature enhancements.
----
