[[structure]]
= Structure

[[admonitions]]
== Admonitions

Admonitions should draw the reader’s attention to certain information. Keep admonitions to a minimum, and avoid placing multiple admonitions close to one another. If multiple admonitions are necessary, restructure the information by moving the less-important statements into the flow of the main content.

Valid admonition types:

NOTE:: Additional guidance or advice that improves product configuration, performance, or supportability.
IMPORTANT:: Advisory information essential to the completion of a task. Users must not disregard this information.
WARNING:: Information about potential system damage, data loss, or a support-related issue if the user disregards this admonition. Explain the problem, cause, and offer a solution that works. If available, offer information to avoid the problem in the future or state where to find more information.
TIP:: Alternative methods that might not be obvious. Makes applying the techniques and procedures described in the text easier or targets specific needs. Helps users understand the benefits and capabilities of the product. Not essential to using the product.

[IMPORTANT]
====
CAUTION, which is another type of AsciiDoc admonition, is not fully supported by the Red{nbsp}Hat Customer Portal. Do not use this admonition type.
====

Admonitions should be short and concise. Do not include procedures in an admonition.

Only individual admonitions are allowed, for example, you cannot have a plural *NOTES* heading.

.Example AsciiDoc
----
[NOTE]
====
Text for note.
====
----

[[lead-in-sentences]]
== Lead-in sentences

A lead-in sentence in this context is the text that directly follows a `Prerequisites` or `Procedure` heading in a task-based module. It is distinct from the module abstract, which describes the goals of the user for the module.

Do not use a lead-in sentence in the `Prerequisites` or `Procedure` sections of a module unless it is necessary to aid navigation or add clarity.

The following examples demonstrate when a lead-in sentence might add value.

* Your module has a long list of prerequisites, and you want to group the prerequisites in sections to make it easier for users to understand what tasks must be performed to complete a procedure.
* Your module has a complex procedure or set of prerequisites, and you want to emphasize that all steps or prerequisites must be completed.

Use a complete sentence for the lead-in sentence to reduce ambiguity and support translation.

[[prerequisites]]
== Prerequisites

When writing prerequisites, be as clear and concise as possible. You can use the passive voice, _if necessary_, to achieve that end.

Write prerequisites as checks that are true or that the user must have completed before they begin a procedure. They can be actions that the user, another person, or piece of technology has completed. Prerequisites can also include items that the user must have ready before beginning the procedure.

* The passive voice might be appropriate for a prerequisite that is not completed by the current user. For example, having a configuration enabled by a system admin.

* Avoid using imperative formations.

* Use parallel language when you write prerequisites. For example, if one bullet is a complete sentence, write the other bullets as complete sentences. But one bullet can be passive voice and another active voice.

.Examples of prerequisites

* JDK 11 or later is installed.
+
Passive voice: the agent is unknown or unimportant.

* A running Kafka instance in {product}.
+
Not a complete sentence: This prerequisite is acceptable if all the other prerequisites in your list are also not complete sentences.

* You are logged in to the Administration Portal.

* You have validated Thing 1.

.Additional resources

* link:https://redhat-documentation.github.io/modular-docs/#creating-procedure-modules[_Procedure Prerequisites_ in the _Modular Documentation Reference Guide_]

[[shortdesc]]
== Short descriptions

To help readers find the information that they need or to confirm that they are in the right place, every module and assembly must include a _short description_, also called an _abstract_.

[IMPORTANT]
====
Do not start a module or assembly with an admonition, even when adding the Technology Preview admonition. Always include a short description before including an admonition.
====

This description is usually at least 2-3 sentences long, and you can scan it in a few seconds. It exists between the title and the main content, connecting them and providing context and disambiguation.

Follow these guidelines when writing short descriptions:

* Include user intent:
** *What* users must do. This content is similar to what is in the title but should not just repeat the same information.
** *Why* users must complete an action. You must build from the information in the title. This content helps users understand why completing an action is important or beneficial to them.
* Make modules findable and reusable. Ensure that the product name is either in the title or the short description of a module or assembly.
* If you are documenting two or more ways of completing the same procedure, explain why users would want to choose one or the other. If possible, link to the other ways.
* For complex procedures, include some of the key tasks that a customer must complete.
* Write in plain English and use simple sentences. You can test the reading level of your sentences by using a readability scoring tool.
* Use active voice and present tense.
* Avoid self-referential language, such as "This topic covers..." or "Use this procedure to...".
* Avoid feature-focused language. Focus on what users can accomplish with a product, not on what a product does. For example, avoid phrases such as "This product allows you to...".
* Use customer-centric language, such as "You can... by..." or "To..., configure...".

.Example short description 1
--
====
==== Creating a group and adding a system

Group many systems together in the Edge Management application [*what*] to manage them more easily [*why*]. For example, you can more easily mitigate vulnerabilities and update systems that are alike.
====
--

.Example short description 2
--
====
==== Creating a Kafka instance in OpenShift Streams for Apache Kafka

To connect OpenShift Streams for Apache Kafka to other applications or services [*why*], create and configure a Kafka instance in the web console [*what*]. A Kafka instance in OpenShift Streams for Apache Kafka includes the following items:

* A Kafka cluster
* A bootstrap server
* The configurations needed to connect to producer and consumer services
====
--

// TODO: Add new style entries alphabetically in this file
