[[support]]
= Support

[[developer-preview-guidance]]
== Developer Preview

Developer Preview software provides early access to a technology, component, or feature in advance of its possible inclusion in a Red Hat product offering. Customers can use Developer Preview software to test functionality and provide feedback during the development process. Documentation is not required for Developer Preview software, but if documentation is provided, it is subject to change or removal at any time. Also, testing is limited for Developer Preview software. Red Hat might provide ways to submit feedback on Developer Preview software without an associated SLA.

[WARNING]
====
Some products, such as Openshift Container Platform,  do not include Developer Preview content in the documentation. Check with your Content Strategist or Support contact to confirm whether you can publish Developer Preview documentation for your product.
====

When documenting a Developer Preview software, follow these guidelines:

* Add an admonition labeled **IMPORTANT** at the beginning of the Developer Preview content and include the template text.

* Use initial uppercase capitalization, that is, Developer Preview.

* Never use the phrase "supported as a Developer Preview", and avoid using "support" in Developer Preview descriptions. Instead, use neutral words like "available", "provide", "capability", and so on.

* When the Developer Preview software becomes generally available, remove the IMPORTANT admonition from any document that includes content about the feature.
+
[NOTE]
====
You might need to replace the Developer Preview admonition with a Technology Preview admonition. For more information, see <<Technology Preview>>.
====

Use the following template. Replace _<software_name>_ with the software name:

.Example AsciiDoc: Developer Preview admonition template
[source,text,subs="+quotes"]
----
[IMPORTANT]
====
_<software_name>_ is Developer Preview software only. Developer Preview software is not supported by Red Hat in any way and is not functionally complete or production-ready. Do not use Developer Preview software for production or business-critical workloads. Developer Preview software provides early access to upcoming product software in advance of its possible inclusion in a Red Hat product offering. Customers can use this software to test functionality and provide feedback during the development process. This software might not have any documentation, is subject to change or removal at any time, and has received limited testing. Red Hat might provide ways to submit feedback on Developer Preview software without an associated SLA.

For more information about the support scope of Red Hat Developer Preview software, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====
----

.Examples of possible values for _<software_name>_

* NUMA-aware scheduling
* Node Health Check Operator
* CSI inline ephemeral volumes

For more information about the support scope of Red Hat Developer Preview features, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope]. For a comparison of Developer Preview and Technology Preview features, see link:https://access.redhat.com/articles/6966848[Developer and Technology Previews: How they compare].

[[technology-preview-guidance]]
== Technology Preview

Technology Preview features provide early access to upcoming product innovations, enabling customers to test functionality and provide feedback during the development process. However, these features are not fully supported. Documentation for a Technology Preview feature might be incomplete or include only basic installation and configuration information.

When documenting a Technology Preview feature, follow these guidelines:

* Add an admonition labeled IMPORTANT at the beginning of the Technology Preview content and include the template text.
* Use initial uppercase capitalization, that is, Technology Preview.
* Include a brief description of the Technology Preview feature in the release notes.
* Maintain a list of features that are currently in Technology Preview status in the release notes.
* Never use the phrase "supported as a Technology Preview", and avoid using "support" in Technology Preview descriptions. Instead, use neutral words like "available", "provide", "capability", and so on.
* When the Technology Preview feature becomes generally available, remove the IMPORTANT admonition from the release notes and any other document that includes content about the feature.

Use the following template text verbatim, where _<feature_name>_ is your feature name:

.Example AsciiDoc: Technology Preview admonition template
[source,text,subs="+quotes"]
----
[IMPORTANT]
====
_<feature_name>_ is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
----

.Examples of possible values for _<feature_name>_

* The Driver Toolkit
* SSPI connection support on Microsoft Windows
* Hot-plugging virtual disks

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope]. For a comparison of Developer Preview and Technology Preview features, see link:https://access.redhat.com/articles/6966848[Developer and Technology Previews: How they compare].

// TODO: Add new style entries alphabetically in this file
